name: CI/CD

on: [push]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.2.0

      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          start: yarn serve build -p 3000 -s
          build: yarn build
          wait-on: http://localhost:3000
        env:
          REACT_APP_GRAPHQL_API_URL: https://dev.stately.ai/registry/api/graphql
          CI: 'false'

      - name: Upload Screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Videos
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
